name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Install Dependencies
        run:
          npm ci
          npm run build && ls

      - name: Push
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.TOKEN_FOR_IO }}
          BRANCH: master
          FOLDER: next-blog/out
          REPOSITORY_NAME: bourneo/bourneo.github.io
#          TARGET_FOLDER: github-actions-demo # 打包的文件将放到静态服务器 github-actions-demo 目录下
#        run: |
#          git init
#          git checkout -b master
#          git add -A
#          # 这里把下面所有 `<YOUR_NAME>/<YOUR_EMAIL>/<COMMIT_MSG>/<YOUR_TOKEN>` 替换成你自己的就可以了
#          git -c user.name='b' -c user.email='e' commit -m 'up'
#          # 这里需要一个 共开仓库 的 secrets 配置，这里的 secrets 是一个环境变量，可以直接拿过来直接用
#          git remote add origin https://${{secrets.TOKEN_FOR_IO}}@github.com/bourneo/bourneo.github.io.git
#          git push origin main -f -q
